PROGS := Assgn2

all: $(PROGS)

Assgn2: main.cpp Item.cpp Item.h GroceryList.cpp GroceryList.h 
	g++ -g main.cpp Item.cpp Item.h GroceryList.cpp GroceryList.h  -o Assgn2
	
clean:
	rm -f $(PROGS) *.o*~