PROGS := Lab10

all: $(PROGS)

Lab9: main.cpp FibonacciR.cpp FibonacciR.h FibonacciNR.cpp FibonacciNR.h
	g++ -g main.cpp FibonacciR.cpp FibonacciR.h FibonacciNR.cpp FibonacciNR.h  -o Lab10
	
clean:
	rm -f $(PROGS) *.o*~